---
title: "Pollution Data Group Data Management Plan"
author: "Elise, Mitchell, Steph and Dannique"
<<<<<<< HEAD
date: "January 28, 2016"
=======
>>>>>>> fd75f8e54ede8c182934485a7fb543676688ba88
output: html_document
theme: lumen
---

#### Types of Data
Data will be spreadsheets on contaminant concentrations and companion descriptior variables (location, location descriptors, timestamps, etc.).
Data will be saved in .csv files.
Data will be sourced from existing datasets online and processed in R, with collaboration through GitHub.


#### Data and Metadata Standards
Metadata will be saved in a corresponding .txt file (eg EUSO2.csv has a companion EUSO2.txt metadata file.) This file will describe the data source, variables and units, date of download, of the data in the .csv file.

#### Policies for Access and Sharing
All data will be readily available through GitHub @pollute.  Requests for forking will enable access to the data and associated processing code. The R Programming Software will be nessisary to view and process the data in this manner. Forseeable users include instructors and other students in the Environmental Informatics course.

#### Policies and Provisions for Re-Use, Re-Distribution
Only existing data will be used, so no delay will be present in data availability. Our processing of the data will be live on GitHub for anyone to fork. No limitations will be placed on the data in terms of privacy.

#### Plans for Archiving and Preservation of Access
Data, metadata and processing code will be preserved on the @pollute GitHub repository at least until the end of the Winter 2016 quarter, and possibly for longer.

<<<<<<< HEAD
=======
####Data Question
Here we examine the question... How many monitorining stations in each city in Germany have an SO2 value that exceeds 10?

```{r, echo=FALSE, warning=FALSE}
# Need to include the following functions:
library(readr)
library(dplyr)

EUSO2=read_csv('data/EUSO2.csv')

EUSO2 %T>% 
 select(country_iso_code, city_name, ug_m3) %>% 
 filter(ug_m3 > 10) %>% 
 filter(country_iso_code == 'DE') %>% 
 group_by(city_name)  %>% 
 summarize(n = n())
```
>>>>>>> fd75f8e54ede8c182934485a7fb543676688ba88
